extends: existence
message: 'Use cross references when linking within documentation.'
link: https://asciidoctor.org/docs/user-manual/#xref
nonword: true
level: error
scope: raw
tokens:
  - https?:\/\/vaadin\.com\/docs.*?(\s|\[)
