# Need to keep this as a separate rule in order to let the Versions check work
extends: substitution
message: "Write 'Vaadin' instead of 'vaadin'."
level: error
ignorecase: false
swap:
  vaadin: Vaadin
