extends: existence
message: 'Avoid having explicit mentions about Vaadin versions'
link: https://github.com/vaadin/docs/wiki/Authoring-articles#indicating-new-and-deprecated-features
level: error
ignorecase: false
tokens:
  - Vaadin [0-9]{1,2}
