extends: existence
message: "Don't refer to a specific Vaadin version."
link: https://github.com/vaadin/docs/wiki/Authoring-articles#indicating-new-and-deprecated-features
level: error
ignorecase: true
tokens:
  - Vaadin \d{1,2}
