name: Lint

on: push

jobs:
  writing-style:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          files: __onlyModified
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
